
- name: Test TF CLI
  hosts: localhost
  tasks:
    - name: Template main.tf
      ansible.builtin.template:
        src: ./tfc/main.tf.j2
        dest: ./tfc/main.tf
        mode: '0644'
      delegate_to: localhost

    - name: TF deploy of a service
      cloud.terraform.terraform:
        project_path: './tfc'
        state: absent
        force_init: true
        workspace: Ansible-Content-Integration
